[package]
name = "droute"
version = "0.1.0"
authors = ["Harry Ying <lexugeyky@outlook.com>"]
edition = "2018"
description = "Routing mechanism lib for dcompass the DNS server."
repository = "https://github.com/LEXUGE/dcompass"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trust-dns-client = { version = "^0.19", default-features = false }
trust-dns-https = "^0.19"
trust-dns-proto = "^0.19"
rustls = "^0.17"
async-trait = "^0.1"
webpki-roots = "^0.20"
futures = "^0.3"
tokio = { version = "^0.2", features = ["full"]}
hashbrown = "^0.9"
dmatcher = {version = "^0.1", path = "../dmatcher"}
log = "^0.4"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
thiserror = "^1.0"

[dev-dependencies]
tokio-test = "^0.2"
