[package]
name = "droute"
version = "0.1.0-alpha.1"
authors = ["Harry Ying <lexugeyky@outlook.com>"]
edition = "2018"
description = "Routing mechanism lib for dcompass the DNS server."
repository = "https://github.com/LEXUGE/dcompass"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# DNS-implementation related dependencies
trust-dns-client = { version = "0.20.0-alpha.3", default-features = false }
trust-dns-https = "0.20.0-alpha.3"
trust-dns-proto = "0.20.0-alpha.3"
trust-dns-rustls = "0.20.0-alpha.3"
rustls = {version = "^0.19", features = ["dangerous_configuration"] }
async-trait = "^0.1"
webpki-roots = "^0.20"
webpki = "^0.21"

# Async-aware dependencies
futures = "^0.3"
tokio = { version = "^0.3", features = ["rt-multi-thread", "net", "fs", "macros", "io-util"]}

# Logic-needed dependencies
hashbrown = "^0.9"
dmatcher = {version = "^0.1", path = "../dmatcher"}
log = "^0.4"
serde = { version = "^1.0", features = ["derive", "rc"] }
lru = "^0.6"
thiserror = "^1.0"
lazy_static = "^1.0"

[dev-dependencies]
tokio-test = "^0.3"
criterion = "^0.3"

[[bench]]
name = "benchmark"
harness = false
