[package]
name = "dcompass"
version = "0.1.0"
authors = ["Harry Ying <lexugeyky@outlook.com>"]
edition = "2018"

[dependencies]
tokio-compat-02 = "^0.1"
trust-dns-proto = "^0.19"
droute = {version = "^0.1", path = "../droute"}
futures = "^0.3"
tokio = { version = "^0.3", features = ["full"]}
simple_logger = "^1.11"
clap = { version = "^2.0", features = ["yaml"] }
log = "^0.4"
anyhow = "^1.0"
