name: "Build dcompass on various targets"
on:
  push:
    tags:
      - v*
jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl, armv7-unknown-linux-musleabihf, armv5te-unknown-linux-musleabi, x86_64-pc-windows-gnu, x86_64-apple-darwin, aarch64-unknown-linux-musl]
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: armv7-unknown-linux-musleabihf
            os: ubuntu-latest
          - target: armv5te-unknown-linux-musleabi
            os: ubuntu-latest
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install musl tools
      if: contains(matrix.target, 'musl')
      run: sudo apt-get install musl-tools

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ matrix.target }}

    - uses: actions-rs/install@v0.1
      with:
        crate: cross
        version: latest
        use-tool-cache: true

    - name: Build
      run: cross build --release --locked --target ${{ matrix.target }}

    - name: Strip
      if: ${{ !contains(matrix.target, 'arm') }}
      shell: bash
      run: |
        if [[ "${{ matrix.target }}" == "x86_64-pc-windows-gnu" ]]
        then
          strip ./target/${{ matrix.target }}/release/dcompass.exe
        else
          strip ./target/${{ matrix.target }}/release/dcompass
        fi

    - name: Package
      shell: bash
      run: |
        if [[ "${{ matrix.target }}" == "x86_64-pc-windows-gnu" ]]
        then
          cp ./target/${{ matrix.target }}/release/dcompass.exe ./dcompass-${{ matrix.target }}.exe
        else
          cp ./target/${{ matrix.target }}/release/dcompass ./dcompass-${{ matrix.target }}
        fi

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: 'dcompass*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
