name: "Build dcompass on various targets"
on:
  push:
    tags:
      - v*
jobs:
  release:
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, armv7-unknown-linux-musleabihf, armv5te-unknown-linux-musleabi, x86_64-pc-windows-gnu, x86_64-apple-darwin]
        include:
          - target: x86_64-unknown-linux-musl
            cross: false
            os: ubuntu-latest
            bin: dcompass
          - target: armv7-unknown-linux-musleabihf
            cross: true
            os: ubuntu-latest
            bin: dcompass
          - target: armv5te-unknown-linux-musleabi
            cross: true
            os: ubuntu-latest
            bin: dcompass
          - target: x86_64-pc-windows-msvc
            cross: false
            os: windows-latest
            bin: dcompass.exe
          - target: x86_64-apple-darwin
            cross: false
            os: macos-latest
            bin: dcompass
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ matrix.target }}

    - uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.cross }}
        command: build
        args: --locked --target ${{ matrix.target }}

    - name: Package
      shell: bash
      run: |
        strip target/${{ matrix.target }}/release/${{ matrix.bin }}
        cp ./target/${{ matrix.target }}/release/${{ matrix.bin }} .
    - name: Publish
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: 'dcompass*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
